version: "3.3"

services:
  nginx:
    build: ./nginx
    container_name: ng03
    ports:
      - 1500:80
    volumes:
      - ./flussonic_stat/static:/app/static
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: app03
    expose:
      - 8000
    volumes:
      - ./flussonic_stat:/app
      - ./flussonic_stat/static:/app/static
      - ./db_backup:/backup
    env_file:
      - ./flussonic_stat/.env
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: db03
    image: mysql:latest
    ports:
      - '3306:3306'
    command:
      - '--server-id=1'
      - '--log-bin=mysql-bin'
      - '--binlog-do-db=flussonic'
      - '--binlog-expire-logs-seconds=259200'
    env_file:
      - .env
    restart: always
    volumes:
      - ./db_backup:/backup
      - ./db_mysql:/var/lib/mysql

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mariadb-phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  static:
