version: "3.3"

services:
  nginx:
    build: ./nginx
    container_name: ng02
    ports:
      - 1400:80
    volumes:
      - static:/app/static
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: app02
    expose:
      - 8000
    volumes:
      - ./epg_django:/app
      - static:/app/static
    environment:
      - DB_NAME=epg_db
      - MYSQL_USER=docker-user
      - MYSQL_PASSWORD=test
      - SECRET_KEY=Er8nyD~&!4B^e6H4!#N~m4t8VCrL^f27
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: db02
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'epg_db'
      MYSQL_USER: 'docker-user'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'superpassword'
    restart: always
    volumes:
    - ./db_django:/var/lib/mysql
volumes:
  static:
