version: "3.3"

services:
  nginx:
    build: ./nginx
    container_name: ng03
    ports:
      - 1500:80
    volumes:
      - ./flussonic_stat/static:/app/static
    depends_on:
      - app

  app:
    build:
      context: .
    container_name: app03
    expose:
      - 8000
    volumes:
      - ./flussonic_stat:/app
      - ./flussonic_stat/static:/app/static
    environment:
      - DB_NAME=flussonic_stat
      - MYSQL_USER=flussonic-user
      - MYSQL_PASSWORD=test
      - SECRET_KEY=django-insecure-s(3l57qop!^xrvmkq59xqxdr=4l(&24z)p9oaa32ptfd*x(6s8
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    container_name: db03
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'flussonic_stat'
      MYSQL_USER: 'flussonic-user'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'superpassword'
    restart: always
    volumes:
    - ./db_django:/var/lib/mysql
volumes:
  static:
