# Generated by Django 3.2.8 on 2021-10-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify_channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channellistmodel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
    ]
