# Generated by Django 3.2 on 2023-03-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcemodel',
            old_name='name',
            new_name='url',
        ),
    ]
