# Generated by Django 3.2 on 2024-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_rename_name_sourcemodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermodel',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
