# Generated by Django 3.2.6 on 2021-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField()),
                ('name', models.CharField(max_length=16)),
                ('source', models.GenericIPAddressField()),
                ('ip', models.GenericIPAddressField()),
                ('token', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
    ]
