# Generated by Django 3.2.8 on 2021-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_sessionmodel_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='session_id',
            field=models.CharField(max_length=55),
        ),
    ]
