# Generated by Django 3.2 on 2022-12-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_sessionmodel_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionmodel',
            options={'verbose_name_plural': 'Статистика'},
        ),
    ]
