# Generated by Django 3.2 on 2024-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_sessionmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
