# Generated by Django 3.2.8 on 2021-10-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.BigIntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.BigIntegerField()),
                ('deleted_at', models.BigIntegerField(blank=True)),
                ('ip', models.GenericIPAddressField()),
                ('last_access_time', models.BigIntegerField()),
                ('media', models.CharField(max_length=10)),
                ('session_id', models.CharField(max_length=55)),
                ('token', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('user_agent', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
                'db_table': 'notify_session',
                'ordering': ['created_at'],
            },
        ),
    ]
