# Generated by Django 3.2 on 2022-12-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statussessionmodel',
            name='country',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
