# Generated by Django 3.2.7 on 2021-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statussessionmodel',
            name='deleted_at',
            field=models.BigIntegerField(blank=True),
        ),
    ]
