# Generated by Django 3.2 on 2023-02-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify_session', '0002_alter_statussessionmodel_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statussessionmodel',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
    ]
