# Generated by Django 3.2.7 on 2021-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_session', '0002_alter_statussessionmodel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statussessionmodel',
            name='bytes_sent',
            field=models.BigIntegerField(blank=True),
        ),
    ]
