# Generated by Django 3.2 on 2023-02-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAstraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_channel', models.CharField(max_length=255, unique=True)),
                ('id_astra', models.CharField(max_length=4, unique=True)),
                ('ip_server', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Астра канал',
                'verbose_name_plural': 'Астра каналы',
                'db_table': 'astra_channel',
            },
        ),
        migrations.CreateModel(
            name='OnAirStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('onair', models.BooleanField()),
                ('id_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.channelastramodel')),
            ],
            options={
                'verbose_name': 'Статус канала',
                'verbose_name_plural': 'Статус каналов',
                'db_table': 'onair_status',
            },
        ),
    ]
