# Generated by Django 3.2 on 2023-02-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onairstatusmodel',
            old_name='id_channel',
            new_name='channel_id',
        ),
    ]
