# Generated by Django 3.2 on 2023-02-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_id_channel_onairstatusmodel_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelastramodel',
            name='id_astra',
            field=models.CharField(max_length=4),
        ),
    ]
