# Generated by Django 3.2 on 2023-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_channelastramodel_id_astra'),
    ]

    operations = [
        migrations.AddField(
            model_name='onairstatusmodel',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
